/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.User;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author Hachiko
 */
public class FMGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FMGlavna
     */
    User user;

    public FMGlavna() {
        initComponents();
        jbtnOpet.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrbtnGradovi = new javax.swing.JRadioButton();
        jrbtnPredmeti = new javax.swing.JRadioButton();
        jrbtnTimovi = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jpfPass = new javax.swing.JPasswordField();
        jbtnUlogujSe = new javax.swing.JButton();
        jbtnOpet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonGroup1.add(jrbtnGradovi);
        jrbtnGradovi.setSelected(true);
        jrbtnGradovi.setText("Gradovi Evrope");

        buttonGroup1.add(jrbtnPredmeti);
        jrbtnPredmeti.setText("Predmeti na FON-u");

        buttonGroup1.add(jrbtnTimovi);
        jrbtnTimovi.setText("Fudbalski timovi");

        jLabel1.setText("Dobro dosli u igru vesala!");

        jLabel2.setText("Izaberite kategoriju");

        jLabel3.setText("Email:");

        jLabel4.setText("Password:");

        jbtnUlogujSe.setText("Uloguj se");
        jbtnUlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUlogujSeActionPerformed(evt);
            }
        });

        jbtnOpet.setText("Igraj opet");
        jbtnOpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(jtxtEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jpfPass)))
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jrbtnGradovi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jrbtnPredmeti)
                        .addGap(35, 35, 35)
                        .addComponent(jrbtnTimovi)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnUlogujSe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnOpet)))
                        .addGap(0, 222, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtnGradovi)
                    .addComponent(jrbtnPredmeti)
                    .addComponent(jrbtnTimovi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUlogujSe)
                    .addComponent(jbtnOpet))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUlogujSeActionPerformed
        try {
            user = kreirajUsera();
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.ULOGUJ_SE);
            toZahtev.setParametar(user);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();
            if (toOdgovor.getIzuzetak() == null) {
                int konstanta = Konstante.VRATI_TIMOVE;
                if (jrbtnGradovi.isSelected()) {
                    konstanta = Konstante.VRATI_GRADOVE;
                } else if (jrbtnPredmeti.isSelected()) {
                    konstanta = Konstante.VRATI_PREDMETE;
                }
                FMPogadjanje fm = new FMPogadjanje(this, true, konstanta);
                fm.setVisible(true);
                srediFormu();
            } else {
                throw new Exception((Exception) toOdgovor.getIzuzetak());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnUlogujSeActionPerformed

    private void jbtnOpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpetActionPerformed
        int konstanta = Konstante.VRATI_TIMOVE;
        if (jrbtnGradovi.isSelected()) {
            konstanta = Konstante.VRATI_GRADOVE;
        } else if (jrbtnPredmeti.isSelected()) {
            konstanta = Konstante.VRATI_PREDMETE;
        }
        FMPogadjanje fm = new FMPogadjanje(this, true, konstanta);
        fm.setVisible(true);
    }//GEN-LAST:event_jbtnOpetActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.KRAJ_RADA);
            toZahtev.setParametar(user);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnOpet;
    private javax.swing.JButton jbtnUlogujSe;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JRadioButton jrbtnGradovi;
    private javax.swing.JRadioButton jrbtnPredmeti;
    private javax.swing.JRadioButton jrbtnTimovi;
    private javax.swing.JTextField jtxtEmail;
    // End of variables declaration//GEN-END:variables

    private User kreirajUsera() {
        String email = jtxtEmail.getText().trim();
        String pass = jpfPass.getText().toString();
        System.out.println(pass);
        return new User(email, pass);
    }

    private void srediFormu() {
        jtxtEmail.setEditable(false);
        jpfPass.setEditable(false);
        jbtnUlogujSe.setVisible(false);
        jbtnOpet.setVisible(true);
    }

}
