/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.io.IOException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author Hachiko
 */
public class FMPogadjanje extends javax.swing.JDialog {

    /**
     * Creates new form FMPogadjanje
     */
    int konstanta;

    public FMPogadjanje(java.awt.Frame parent, boolean modal, int konstanta) {
        super(parent, modal);
        initComponents();
        this.konstanta = konstanta;
        srediFormu(konstanta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtRec = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtSlovo = new javax.swing.JTextField();
        jbtnPosalji = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxtIskoriscenaSlova = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPokusaji = new javax.swing.JTextField();
        jbtnPonovo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Vasa rec:");

        jtxtRec.setEditable(false);

        jLabel2.setText("Izaberite slovo:");

        jbtnPosalji.setText("Posalji slovo");
        jbtnPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPosaljiActionPerformed(evt);
            }
        });

        jLabel3.setText("Iskoriscenja slova: ");

        jtxtIskoriscenaSlova.setEditable(false);

        jLabel4.setText("Preostali broj pokusaja:");

        jtxtPokusaji.setEditable(false);

        jbtnPonovo.setText("Igraj ponovo");
        jbtnPonovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPonovoActionPerformed(evt);
            }
        });

        jButton1.setText("Odustani");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtRec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPosalji))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtIskoriscenaSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPokusaji, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnPonovo)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jbtnPosalji))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtIskoriscenaSlova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtPokusaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPonovo)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPosaljiActionPerformed
        try {
            String slovo = jtxtSlovo.getText().trim().toUpperCase();
            if (slovo.isEmpty()) {
                throw new Exception("Morate upisati neko slovo");
            }
            if (slovo.length() > 1) {
                throw new Exception("Morate uneti samo po jedno slovo");
            }
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.PROBAJ_SLOVO);
            toZahtev.setParametar(slovo);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();
            if (toOdgovor.getIzuzetak() == null) {
                if (toOdgovor.getRezultat() == null) {
                    if (!jtxtIskoriscenaSlova.getText().contains(slovo)) {
                        jtxtIskoriscenaSlova.setText(jtxtIskoriscenaSlova.getText() + " " + slovo);
                    }
                    jtxtPokusaji.setText((Integer.parseInt(jtxtPokusaji.getText().trim()) - 1) + "");
                    proveriBrojPokusaja();
                } else {
                    zameniZvezdicu((LinkedList<Integer>) toOdgovor.getRezultat(), slovo.toCharArray()[0]);
                }
            } else {
                JOptionPane.showMessageDialog(this, toOdgovor.getPoruka());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jbtnPosaljiActionPerformed

    private void jbtnPonovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPonovoActionPerformed
        srediFormu(konstanta);
    }//GEN-LAST:event_jbtnPonovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnPonovo;
    private javax.swing.JButton jbtnPosalji;
    private javax.swing.JTextField jtxtIskoriscenaSlova;
    private javax.swing.JTextField jtxtPokusaji;
    private javax.swing.JTextField jtxtRec;
    private javax.swing.JTextField jtxtSlovo;
    // End of variables declaration//GEN-END:variables

    private void srediFormu(int konstanta) {
        jbtnPosalji.setEnabled(true);
        jtxtIskoriscenaSlova.setText(null);
        String rec;
        int pokusaji;
        try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(konstanta);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();
            if (toOdgovor.getIzuzetak() == null) {
                rec = toOdgovor.getRezultat().toString();
                pokusaji = rec.length() + 8 - brojRazmaka(rec);

                jtxtRec.setText(rec);
                jtxtPokusaji.setText(pokusaji + "");
            } else {
                JOptionPane.showMessageDialog(this, toOdgovor.getPoruka());
            }
        } catch (Exception e) {
        }
    }

    private int brojRazmaka(String rec) {
        int broj = 0;
        char[] recNiz = rec.toCharArray();
        for (char c : recNiz) {
            if (Character.isWhitespace(c)) {
                broj++;
            }
        }
        return broj;
    }

    private void zameniZvezdicu(LinkedList<Integer> i, char slovo) throws Exception {
        char[] recNiz = jtxtRec.getText().trim().toCharArray();
        for (Integer j : i) {
            recNiz[j] = slovo;
        }
        jtxtRec.setText(new String(recNiz));
        proveriDaLiJeKraj(recNiz);
    }

    private void proveriBrojPokusaja() throws Exception {
        int broj = Integer.parseInt(jtxtPokusaji.getText().trim());
        if (broj == 0) {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.KRAJ_IGRE);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();
            if (toOdgovor.getIzuzetak() == null) {
                String rec = toOdgovor.getRezultat().toString();
                jtxtRec.setText(rec);
                jbtnPosalji.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, toOdgovor.getPoruka());
            }
            JOptionPane.showMessageDialog(this, "Igra je zavrsena");
        }
    }

    private void proveriDaLiJeKraj(char[] recNiz) throws Exception {
        boolean zvezdice = false;
        for (int i = 0; i < recNiz.length; i++) {
            if (recNiz[i] == '*') {
                zvezdice = true;
            }
        }
        if (!zvezdice) {
            jbtnPosalji.setEnabled(false);
            throw new Exception("Kraj igre! Cestitamo! Pobedili ste");
        }
    }
}
