/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.planeta;

import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import kontroler.planeta.KontrolerPorudzbenice;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Licina
 */
public class FMPorudzbenica extends javax.swing.JDialog {

    /**
     * Creates new form FMPorudzbenica
     */
    KontrolerPorudzbenice kontrolerP;

    public FMPorudzbenica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kontrolerP = new KontrolerPorudzbenice();
        kontrolerP.srediFormu(this);
    }

    public JComboBox getJcbAutobus() {
        return jcbAutobus;
    }

    public JComboBox getJcbPlaneta() {
        return jcbPlaneta;
    }

    public JComboBox getJcbZalihe() {
        return jcbZalihe;
    }

    public JSpinner getJsKolicina() {
        return jsKolicina;
    }

    public JTable getJtblStavke() {
        return jtblStavke;
    }

    public JTextField getJtxtJedinicaMere() {
        return jtxtJedinicaMere;
    }

    public JTextField getJtxtBrojPorudzbenice() {
        return jtxtBrojPorudzbenice;
    }

    public JXDatePicker getJdpDatePicker() {
        return jdpDatum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbAutobus = new javax.swing.JComboBox();
        jcbPlaneta = new javax.swing.JComboBox();
        jlAutobus = new javax.swing.JLabel();
        jlPlaneta = new javax.swing.JLabel();
        jlDatum = new javax.swing.JLabel();
        jpnlStavka = new javax.swing.JPanel();
        jlZalihe = new javax.swing.JLabel();
        jcbZalihe = new javax.swing.JComboBox();
        jlKolicina = new javax.swing.JLabel();
        jsKolicina = new javax.swing.JSpinner();
        jlJedinicaMere = new javax.swing.JLabel();
        jtxtJedinicaMere = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStavke = new javax.swing.JTable();
        jbtnDodajStavku = new javax.swing.JButton();
        jbtnObrisiStavku = new javax.swing.JButton();
        jbtnOdustani = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jlBrojPorudzbenice = new javax.swing.JLabel();
        jtxtBrojPorudzbenice = new javax.swing.JTextField();
        jdpDatum = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiranje nove porudzbenice");

        jcbAutobus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAutobusActionPerformed(evt);
            }
        });

        jcbPlaneta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPlanetaActionPerformed(evt);
            }
        });

        jlAutobus.setText("Autobus:");

        jlPlaneta.setText("Planeta:");

        jlDatum.setText("Datum:");

        jpnlStavka.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavka porudzbenice"));

        jlZalihe.setText("Zalihe:");

        jcbZalihe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlKolicina.setText("Kolicina:");

        jsKolicina.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));

        jlJedinicaMere.setText("Jedinica mere:");

        jtblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblStavke);

        jbtnDodajStavku.setText("Dodaj stavku");
        jbtnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajStavkuActionPerformed(evt);
            }
        });

        jbtnObrisiStavku.setText("Obrisi stavku");
        jbtnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlStavkaLayout = new javax.swing.GroupLayout(jpnlStavka);
        jpnlStavka.setLayout(jpnlStavkaLayout);
        jpnlStavkaLayout.setHorizontalGroup(
            jpnlStavkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlStavkaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlStavkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(jpnlStavkaLayout.createSequentialGroup()
                        .addComponent(jlZalihe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbZalihe, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlStavkaLayout.createSequentialGroup()
                        .addGroup(jpnlStavkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnlStavkaLayout.createSequentialGroup()
                                .addComponent(jlJedinicaMere)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtJedinicaMere, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnlStavkaLayout.createSequentialGroup()
                                .addComponent(jlKolicina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jsKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(jbtnDodajStavku)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnObrisiStavku)))
                .addContainerGap())
        );
        jpnlStavkaLayout.setVerticalGroup(
            jpnlStavkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlStavkaLayout.createSequentialGroup()
                .addGroup(jpnlStavkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlZalihe)
                    .addComponent(jcbZalihe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlStavkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlKolicina)
                    .addComponent(jsKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlStavkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlJedinicaMere)
                    .addComponent(jtxtJedinicaMere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDodajStavku)
                    .addComponent(jbtnObrisiStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbtnOdustani.setText("Odustani");
        jbtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdustaniActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj porudzbenicu");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jlBrojPorudzbenice.setText("Broj porudzbenice:");

        jtxtBrojPorudzbenice.setEditable(false);

        jdpDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpDatumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlStavka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlPlaneta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAutobus)
                                    .addComponent(jlDatum)
                                    .addComponent(jlBrojPorudzbenice))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcbAutobus, 0, 259, Short.MAX_VALUE)
                                            .addComponent(jtxtBrojPorudzbenice)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(jdpDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnOdustani)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBrojPorudzbenice)
                    .addComponent(jtxtBrojPorudzbenice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAutobus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAutobus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPlaneta)
                    .addComponent(jcbPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDatum)
                    .addComponent(jdpDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnlStavka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOdustani)
                    .addComponent(jbtnSacuvaj)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        kontrolerP.sacuvajPorudzbenicu(this);
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiStavkuActionPerformed
        kontrolerP.obrisiStavku(this);
    }//GEN-LAST:event_jbtnObrisiStavkuActionPerformed

    private void jbtnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajStavkuActionPerformed
        kontrolerP.dodajStavku(this);
    }//GEN-LAST:event_jbtnDodajStavkuActionPerformed

    private void jbtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnOdustaniActionPerformed

    private void jcbAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAutobusActionPerformed
        kontrolerP.azurirajSifru(this);
    }//GEN-LAST:event_jcbAutobusActionPerformed

    private void jcbPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPlanetaActionPerformed
        kontrolerP.azurirajSifru(this);
    }//GEN-LAST:event_jcbPlanetaActionPerformed

    private void jdpDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpDatumActionPerformed
        kontrolerP.azurirajSifru(this);
    }//GEN-LAST:event_jdpDatumActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajStavku;
    private javax.swing.JButton jbtnObrisiStavku;
    private javax.swing.JButton jbtnOdustani;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbAutobus;
    private javax.swing.JComboBox jcbPlaneta;
    private javax.swing.JComboBox jcbZalihe;
    private org.jdesktop.swingx.JXDatePicker jdpDatum;
    private javax.swing.JLabel jlAutobus;
    private javax.swing.JLabel jlBrojPorudzbenice;
    private javax.swing.JLabel jlDatum;
    private javax.swing.JLabel jlJedinicaMere;
    private javax.swing.JLabel jlKolicina;
    private javax.swing.JLabel jlPlaneta;
    private javax.swing.JLabel jlZalihe;
    private javax.swing.JPanel jpnlStavka;
    private javax.swing.JSpinner jsKolicina;
    private javax.swing.JTable jtblStavke;
    private javax.swing.JTextField jtxtBrojPorudzbenice;
    private javax.swing.JTextField jtxtJedinicaMere;
    // End of variables declaration//GEN-END:variables

}
