/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.planeta;

import domen.Planeta;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import kontroler.planeta.KontrolerUnosPlanete;

/**
 *
 * @author Licina
 */
public class FMUnosPlanete extends javax.swing.JDialog {

    /**
     * Creates new form FMUnosPlanete
     */
    KontrolerUnosPlanete kontrolerUP;
    public FMUnosPlanete(java.awt.Frame parent, boolean modal, Planeta p) {
        super(parent, modal);
        initComponents();
        kontrolerUP = new KontrolerUnosPlanete();
        kontrolerUP.setPlaneta(p);
        kontrolerUP.srediFormu(this);
        
    }

    public JSpinner getJsUdaljenost() {
        return jsUdaljenost;
    }

    public JTextField getJtxtKoordinate() {
        return jtxtKoordinate;
    }

    public JTextField getJtxtNaziv() {
        return jtxtNaziv;
    }

    public JButton getJbtnSacuvaj() {
        return jbtnSacuvaj;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNaziv = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jtxtKoordinate = new javax.swing.JTextField();
        jlKoordinate = new javax.swing.JLabel();
        jlUdaljenost = new javax.swing.JLabel();
        jsUdaljenost = new javax.swing.JSpinner();
        jlAU = new javax.swing.JLabel();
        jbtnOdustani = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jlAUKoordinate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos nove planete");

        jlNaziv.setText("Naziv:");

        jlKoordinate.setText("Koordinate:");

        jlUdaljenost.setText("Udaljenost od zemlje:");

        jsUdaljenost.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.01d)));

        jlAU.setText("AU");

        jbtnOdustani.setText("Odustani");
        jbtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdustaniActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jlAUKoordinate.setText("AU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNaziv)
                    .addComponent(jlKoordinate)
                    .addComponent(jlUdaljenost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsUdaljenost, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlAU))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtKoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlAUKoordinate)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnOdustani)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNaziv)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtKoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlKoordinate)
                    .addComponent(jlAUKoordinate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUdaljenost)
                    .addComponent(jsUdaljenost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOdustani)
                    .addComponent(jbtnSacuvaj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        kontrolerUP.sacuvajPlanetu(this);
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdustaniActionPerformed
       kontrolerUP.odustani(this);
    }//GEN-LAST:event_jbtnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnOdustani;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JLabel jlAU;
    private javax.swing.JLabel jlAUKoordinate;
    private javax.swing.JLabel jlKoordinate;
    private javax.swing.JLabel jlNaziv;
    private javax.swing.JLabel jlUdaljenost;
    private javax.swing.JSpinner jsUdaljenost;
    private javax.swing.JTextField jtxtKoordinate;
    private javax.swing.JTextField jtxtNaziv;
    // End of variables declaration//GEN-END:variables

}
